# ## How to use this on a new repository:
#
# 1. Copy this file to your repository.
# 1. Create a rule in your repository
# 1. Update the this file in your repository environemnt variable the the rule_id that was just created
# 1. Make sure to have a `GH_TOKEN` secret that is given sufficent permissions to Admin the Repository. Namely Repository Administration Read Write Access (can be created as a fine grained token).
# 1. Enjoy!

name: Code Freeze
run-name: Code Freeze ${{ inputs.code_freeze }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      code_freeze:
        description: Code Freeze Status
        type: choice
        options:
          - active
          - inactive
        default: active
        required: true

jobs:
  code_freeze_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          if [ "active" == "${{ inputs.code_freeze }}" ]; then
            echo "RULE_STATUS=active" >> $GITHUB_ENV
          else
            echo "RULE_STATUS=disabled" >> $GITHUB_ENV
          fi

      - name: Code Freeze
        env:
          GITHUB_RULE_ID: ${{ vars.CODE_FREEZE_RULESET_ID }}
        run: |
          curl \
            -f \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/rulesets/${{ env.GITHUB_RULE_ID }}" \
            -d '{
            "name": "Code Freeze",
            "target": "branch",
            "source_type": "Repository",
            "source": "${{ github.repository }}",
            "enforcement": "${{ env.RULE_STATUS }}",
            "conditions": {
              "ref_name": {
                "exclude": [],
                "include": [
                  "~DEFAULT_BRANCH"
                ]
              }
            },
            "rules": [
              {
                "type": "non_fast_forward"
              },
              {
                "type": "update"
              }
            ],
            "bypass_actors": []
          }'
